### ISSUE TITLE
deployment on heroku reports "unhandled loader in the production webpack config"

### ISSUE THREAD

**Issue by gosuri** [project-serum/serum-dex-ui#54]
Deployment on heroku fails with the below error:

```
2020-12-04T16:23:44.892498+00:00 heroku[web.1]: State changed from crashed to starting
2020-12-04T16:24:04.171691+00:00 heroku[web.1]: Starting process with command `npm start`
2020-12-04T16:24:07.586564+00:00 app[web.1]:
2020-12-04T16:24:07.586605+00:00 app[web.1]: > serum-dex-ui@0.1.0 start /app
2020-12-04T16:24:07.586606+00:00 app[web.1]: > craco start
2020-12-04T16:24:07.586606+00:00 app[web.1]:
2020-12-04T16:24:10.119915+00:00 app[web.1]: /app/node_modules/@craco/craco/lib/plugin-utils.js:29
2020-12-04T16:24:10.119937+00:00 app[web.1]: throw new Error(
2020-12-04T16:24:10.119938+00:00 app[web.1]: ^
2020-12-04T16:24:10.119938+00:00 app[web.1]:
2020-12-04T16:24:10.119939+00:00 app[web.1]: Error: Found an unhandled loader in the production webpack config: /app/node_modules/style-loader/index.js
2020-12-04T16:24:10.119940+00:00 app[web.1]:
2020-12-04T16:24:10.119941+00:00 app[web.1]: This error probably occurred because you updated react-scripts or craco. Please try updating craco-less to the latest version:
2020-12-04T16:24:10.119941+00:00 app[web.1]:
2020-12-04T16:24:10.119941+00:00 app[web.1]: $ yarn upgrade craco-less
2020-12-04T16:24:10.119942+00:00 app[web.1]:
2020-12-04T16:24:10.119942+00:00 app[web.1]: Or:
2020-12-04T16:24:10.119942+00:00 app[web.1]:
2020-12-04T16:24:10.119943+00:00 app[web.1]: $ npm update craco-less
2020-12-04T16:24:10.119943+00:00 app[web.1]:
2020-12-04T16:24:10.119944+00:00 app[web.1]: If that doesn't work, craco-less needs to be fixed to support the latest version.
2020-12-04T16:24:10.119945+00:00 app[web.1]: Please check to see if there's already an issue in the FormAPI/craco-less repo:
2020-12-04T16:24:10.119945+00:00 app[web.1]:
2020-12-04T16:24:10.119945+00:00 app[web.1]: * https://github.com/FormAPI/craco-less/issues?q=is%3Aissue+webpack+unknown+rule
2020-12-04T16:24:10.119946+00:00 app[web.1]:
2020-12-04T16:24:10.119946+00:00 app[web.1]: If not, please open an issue and we'll take a look. (Or you can send a PR!)
2020-12-04T16:24:10.119946+00:00 app[web.1]:
2020-12-04T16:24:10.119947+00:00 app[web.1]: You might also want to look for related issues in the craco and create-react-app repos:
2020-12-04T16:24:10.119947+00:00 app[web.1]:
2020-12-04T16:24:10.119947+00:00 app[web.1]: * https://github.com/sharegate/craco/issues?q=is%3Aissue+webpack+unknown+rule
2020-12-04T16:24:10.119948+00:00 app[web.1]: * https://github.com/facebook/create-react-app/issues?q=is%3Aissue+webpack+unknown+rule
2020-12-04T16:24:10.119948+00:00 app[web.1]:
2020-12-04T16:24:10.119948+00:00 app[web.1]: at throwUnexpectedConfigError (/app/node_modules/@craco/craco/lib/plugin-utils.js:29:11)
2020-12-04T16:24:10.119948+00:00 app[web.1]: at throwError (/app/node_modules/craco-less/lib/craco-less.js:14:5)
2020-12-04T16:24:10.119949+00:00 app[web.1]: at /app/node_modules/craco-less/lib/craco-less.js:119:7
2020-12-04T16:24:10.119950+00:00 app[web.1]: at Array.forEach (<anonymous>)
2020-12-04T16:24:10.119950+00:00 app[web.1]: at Object.overrideWebpackConfig (/app/node_modules/craco-less/lib/craco-less.js:51:11)
2020-12-04T16:24:10.119950+00:00 app[web.1]: at overrideWebpack (/app/node_modules/@craco/craco/lib/features/plugins.js:42:40)
2020-12-04T16:24:10.119951+00:00 app[web.1]: at /app/node_modules/@craco/craco/lib/features/plugins.js:64:29
2020-12-04T16:24:10.119951+00:00 app[web.1]: at Array.forEach (<anonymous>)
2020-12-04T16:24:10.119951+00:00 app[web.1]: at applyWebpackConfigPlugins (/app/node_modules/@craco/craco/lib/features/plugins.js:63:29)
2020-12-04T16:24:10.119952+00:00 app[web.1]: at mergeWebpackConfig (/app/node_modules/@craco/craco/lib/features/webpack/merge-webpack-config.js:67:30)
2020-12-04T16:24:10.159939+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2020-12-04T16:24:10.160498+00:00 app[web.1]: npm ERR! errno 1
2020-12-04T16:24:10.171269+00:00 app[web.1]: npm ERR! serum-dex-ui@0.1.0 start: `craco start`
2020-12-04T16:24:10.171584+00:00 app[web.1]: npm ERR! Exit status 1
2020-12-04T16:24:10.172976+00:00 app[web.1]: npm ERR!
2020-12-04T16:24:10.173259+00:00 app[web.1]: npm ERR! Failed at the serum-dex-ui@0.1.0 start script.
2020-12-04T16:24:10.175087+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-12-04T16:24:10.200505+00:00 app[web.1]:
2020-12-04T16:24:10.205072+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2020-12-04T16:24:10.205233+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2020-12-04T16_24_10_176Z-debug.log
2020-12-04T16:24:10.297369+00:00 heroku[web.1]: Process exited with status 1
2020-12-04T16:24:10.353145+00:00 heroku[web.1]: State changed from starting to crashed

```

**Comment by gosuri** [comment]
Related to docspring/craco-less#30
